apiVersion: v1
kind: Service
metadata:
  name: k8s-app-foo
  labels:
    app.kubernetes.io/name: k8s-app-foo
spec:
  selector:
    app.kubernetes.io/name: k8s-app-foo
  ports:
    - protocol: TCP
      port: 8080